extends Node
const ENUMS = preload("res://enums.gd")
const ADJACENT = {
	ENUMS.BODYPARTS.HEAD: [ENUMS.BODYPARTS.NECK],
	ENUMS.BODYPARTS.NECK: [ENUMS.BODYPARTS.HEAD, ENUMS.BODYPARTS.THORAX],
	ENUMS.BODYPARTS.THORAX: [ENUMS.BODYPARTS.NECK, ENUMS.BODYPARTS.STOMACH, ENUMS.BODYPARTS.LEFTSHOULDER, ENUMS.BODYPARTS.RIGHTSHOULDER],
	ENUMS.BODYPARTS.STOMACH: [ENUMS.BODYPARTS.THORAX, ENUMS.BODYPARTS.LEFTTHIGH, ENUMS.BODYPARTS.RIGHTTHIGH],
	ENUMS.BODYPARTS.LEFTSHOULDER: [ENUMS.BODYPARTS.LEFTARM],
	ENUMS.BODYPARTS.RIGHTSHOULDER: [ENUMS.BODYPARTS.RIGHTARM],
	ENUMS.BODYPARTS.LEFTARM: [ENUMS.BODYPARTS.LEFTSHOULDER],
	ENUMS.BODYPARTS.RIGHTARM: [ENUMS.BODYPARTS.RIGHTSHOULDER],
	ENUMS.BODYPARTS.LEFTTHIGH: [ENUMS.BODYPARTS.LEFTFOOT],
	ENUMS.BODYPARTS.RIGHTTHIGH: [ENUMS.BODYPARTS.RIGHTFOOT],
	ENUMS.BODYPARTS.LEFTFOOT: [],
	ENUMS.BODYPARTS.RIGHTFOOT: [],
}
