extends Object
enum BODYPARTS{
	HEAD,
	NECK,
	THORAX,
	STOMACH,
	LEFTSHOULDER,
	RIGHTSHOULDER,
	LEFTARM,
	RIGHTARM,
	LEFTTHIGH,
	RIGHTTHIGH,
	LEFTFOOT,
	RIGHTFOOT,
}
enum INJURY{
	BLEED,
	BONEBROKEN,
	SCRATCH,
	PAIN,
	BULLET,
	BLACKEDOUT
}
enum ITEMS{
	#BANDAGEDIRTY,
	BANDAGE,
	SPLINT,
	PAINKILLER,
	SURGERYKIT
}
enum HEALITEMS{
	SMALLMEDKIT
}
const bodypart_max_health = {
	BODYPARTS.HEAD: 35,
	BODYPARTS.NECK: 20,
	BODYPARTS.THORAX: 85,
	BODYPARTS.STOMACH: 65,
	BODYPARTS.LEFTTHIGH: 60,
	BODYPARTS.RIGHTTHIGH: 60,
	BODYPARTS.LEFTFOOT: 50,
	BODYPARTS.RIGHTFOOT: 50,
	BODYPARTS.LEFTSHOULDER: 45,
	BODYPARTS.RIGHTSHOULDER: 45,
	BODYPARTS.LEFTARM: 40,
	BODYPARTS.RIGHTARM: 40
}
#func get_enum_name(enum_dict: Dictionary, value: int) -> String:
	#for name in enum_dict.keys():
		#if enum_dict[name] == value:
			#return name
	#return "Unknown"
